spring:
  datasource:
    url: jdbc:mariadb://172.20.0.106:3306/dreamsearch
    username: tgkim
    password: xorkd540!!
    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    timeout: 5000
mybatis:
  type-aliases-package: com.example.test
  mapper-locations: mybatis/mapper/*.xml



